version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - .:/web
      - /web/node_modules
    environment:
      - NODE_ENV=development
